[setup]
nixPkgs = [
    "chromium",
    "chromedriver",
    "nss",
    "fontconfig",
    "freetype",
    "gcc",           # libstdc++.so.6
    "libglvnd",      # libGL.so.1 provider on Nix
    "glib",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libSM",
    "xorg.libICE",
    "xorg.libXrender",
    "freetype",
    "fontconfig",
    "zlib"
]
