# nixpacks.toml
[phases.setup]
nixPkgs = [
    "chromium",
    "chromedriver",
    "nss",
    "fontconfig",
    "freetype",
    "gcc",           # libstdc++.so.6
    "libglvnd",      # libGL.so.1 provider on Nix
    "glib",
    "xorg.libX11",
    "xorg.libXext",
    "xorg.libSM",
    "xorg.libICE",
    "xorg.libXrender",
    "freetype",
    "fontconfig",
    "zlib"
]


[phases.install]
commands = [
  "python -m venv --copies /opt/venv",
  ". /opt/venv/bin/activate",
  # point at the correct file in backend:
  "pip install -r backend/requirements.txt"
]

[phases.start]
cmd = "cd backend && gunicorn server:app --bind 0.0.0.0:${PORT} --workers 2 --timeout 120"
