[setup]
nixPkgs = [
  "gcc",           # provides libstdc++.so.6
  "libstdcxx5",    # older libstdc++ just in case
  "mesa",
  "glib",
  "xorg.libX11",
  "xorg.libXext",
  "xorg.libSM",
  "xorg.libICE",
  "xorg.libXrender",
  "freetype",
  "fontconfig",
  "zlib"
]
